apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-tester
  labels:
    app: clickhouse
spec:
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - kind-worker
      containers:
        - name: clickhouse-tester
          image: projects.registry.vmware.com/antrea/flow-visibility-clickhouse-tester
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          imagePullPolicy: IfNotPresent